version: 2
updates:
# Update packages
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: dev
  commit-message:
    prefix: chore
    include: scope
